<?php
/*************************************************************************************************
 * Copyright 2023 JPL TSolucio, S.L. -- This file is a part of TSOLUCIO coreBOS Tests.
 * The MIT License (MIT)
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *************************************************************************************************/

use PHPUnit\Framework\TestCase;

class ClickHouseWSTest extends TestCase {

	private $records = array(
		array('ctoid' => 1, 'age' => 23, 'firstn' => 'M', 'lastn' => 'S'),
		array('ctoid' => 2, 'age' => 32, 'firstn' => 'S', 'lastn' => 'M'),
		array('ctoid' => 3, 'age' => 33, 'firstn' => 'A', 'lastn' => 'S'),
	);

	/**
	 * Method testQuery
	 * @test
	 */
	public function testQuery() {
		$actual = vtws_query('select * from contactinfo', Users::getActiveAdminUser());
		$this->assertEquals($this->records, $actual, 'CH WS table query');
	}

	/**
	 * Method testCRUD
	 * @test
	 */
	public function testCRUD() {
		$user = Users::getActiveAdminUser();
		$desc = vtws_describe('contactinfo', $user);
		$wsid = $desc['idPrefix'];
		$expected = array(
			'label' => 'contactinfo',
			'label_raw' => 'contactinfo',
			'name' => 'contactinfo',
			'createable' => true,
			'updateable' => true,
			'deleteable' => true,
			'retrieveable' => true,
			'fields' => array(
				0 => array(
					'name' => 'id',
					'label' => 'ctoid',
					'label_raw' => 'ctoid',
					'mandatory' => false,
					'type' => array(
						'name' => 'autogenerated',
					),
					'nullable' => false,
					'editable' => false,
					'default' => '',
				),
				1 => array(
					'name' => 'age',
					'label' => 'age',
					'label_raw' => 'age',
					'mandatory' => true,
					'type' => array(
						'name' => 'Int32',
					),
					'nullable' => false,
					'editable' => true,
				),
				2 => array(
					'name' => 'firstn',
					'label' => 'firstn',
					'label_raw' => 'firstn',
					'mandatory' => true,
					'type' => array(
						'name' => 'String',
					),
					'nullable' => false,
					'editable' => true,
				),
				3 => array(
					'name' => 'lastn',
					'label' => 'lastn',
					'label_raw' => 'lastn',
					'mandatory' => true,
					'type' => array(
						'name' => 'String',
					),
					'nullable' => false,
					'editable' => true,
				),
			),
			'idPrefix' => '62',
			'isEntity' => false,
			'labelFields' => '',
			'filterFields' => array(
				'fields' => '',
				'linkfields' => '',
				'pagesize' => 40,
			),
			'relatedModules' => array(),
		);
		$this->assertEquals($expected, $desc, 'CH WS table describe');
		$entity = array('ctoid' => 4, 'age' => '44', 'firstn' => '4', 'lastn' => '4');
		$actual = vtws_create('contactinfo', $entity, $user);
		$this->assertEquals($entity, $actual, 'CH WS table create');
		$actual = vtws_retrieve($wsid.'x4', $user);
		unset($entity['ctoid']);
		$entity['id'] = $wsid.'x4';
		$this->assertEquals($entity, $actual, 'CH WS table retrieve');
		vtws_revise(array('id'=>$wsid.'x4', 'age'=>5), $user);
		$actual = vtws_retrieve($wsid.'x4', $user);
		$updated = $entity;
		$updated['age'] = '5';
		$this->assertEquals($updated, $actual, 'CH WS table revise');
		$actual = vtws_delete($wsid.'x4', $user);
		$this->assertEquals(['status' => 'successful'], $actual, 'CH WS table delete');
	}
}
?>