<?php
/*************************************************************************************************
 * Copyright 2016 JPL TSolucio, S.L. -- This file is a part of TSOLUCIO coreBOS Tests.
 * The MIT License (MIT)
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute,
 * sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
 * NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *************************************************************************************************/

class VtigerModuleOperation_QueryTest extends PHPUnit_Framework_TestCase {

	public static $vtModuleOperation = null;

	public static function setUpBeforeClass() {
		global $adb, $current_user, $log;
		$current_user = Users::getActiveAdminUser();
		$webserviceObject = VtigerWebserviceObject::fromName($adb,'Accounts');
		self::$vtModuleOperation = new VtigerModuleOperation($webserviceObject, $current_user, $adb, $log);
	}

	public function testStandardVTQL() {
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select firstname, lastname from Leads order by firstname desc limit 0,2;');
		$this->assertEquals("SELECT vtiger_leaddetails.firstname,vtiger_leaddetails.lastname,vtiger_leaddetails.leadid FROM vtiger_leaddetails LEFT JOIN vtiger_crmentity ON vtiger_leaddetails.leadid=vtiger_crmentity.crmid   WHERE  vtiger_crmentity.deleted=0 and vtiger_leaddetails.converted=0 ORDER BY vtiger_leaddetails.firstname DESC LIMIT 0,2;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select accountname from Accounts;');
		$this->assertEquals("SELECT vtiger_account.accountname,vtiger_account.accountid FROM vtiger_account LEFT JOIN vtiger_crmentity ON vtiger_account.accountid=vtiger_crmentity.crmid   WHERE  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
	}

	public function testIncorrectModule() {
		$this->setExpectedException('WebServiceException');
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select nofield from NoModule;');
	}

	public function testIncorrectField() {
		$this->setExpectedException('WebServiceException');
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select accountname,nofield from Accounts;');
	}

	public function testConditions() {
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website from Accounts where website like '%vt%';");
		$this->assertEquals("SELECT vtiger_account.accountname,vtiger_account.website,vtiger_account.accountid FROM vtiger_account LEFT JOIN vtiger_crmentity ON vtiger_account.accountid=vtiger_crmentity.crmid   WHERE (vtiger_account.website LIKE '%vt%') AND  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname from Contacts where firstname like '%o%' order by firstname desc limit 0,22;");
		$this->assertEquals("SELECT vtiger_contactdetails.firstname,vtiger_contactdetails.lastname,vtiger_contactdetails.contactid FROM vtiger_contactdetails LEFT JOIN vtiger_crmentity ON vtiger_contactdetails.contactid=vtiger_crmentity.crmid   WHERE (vtiger_contactdetails.firstname LIKE '%o%') AND  vtiger_crmentity.deleted=0 ORDER BY vtiger_contactdetails.firstname DESC LIMIT 0,22;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website from Accounts where website in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("SELECT vtiger_account.accountname,vtiger_account.website,vtiger_account.accountid FROM vtiger_account LEFT JOIN vtiger_crmentity ON vtiger_account.accountid=vtiger_crmentity.crmid   WHERE (vtiger_account.website IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) AND  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where website in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.website IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where Accounts.website in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.website IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) ) AND vtiger_account.accountid > 0 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website from Accounts where website not in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.website  NOT IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where website not in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.website  NOT IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where Accounts.website not in ('www.edfggrouplimited.com','www.gooduivtiger.com');");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.website  NOT IN ('www.edfggrouplimited.com','www.gooduivtiger.com')) ) AND vtiger_account.accountid > 0 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL('select accountname,website,Accounts.accountname,Accounts.website from Accounts;');
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where website like '%vt%'");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.website LIKE '%vt%') ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select accountname,website,Accounts.accountname,Accounts.website from Accounts where Accounts.website like '%vt%'");
		$this->assertEquals("select vtiger_account.accountname, vtiger_account.website, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.website LIKE '%vt%') ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select id, accountname, Accounts.accountname from Accounts where accountname != 'PK UNA' limit 10");
		$this->assertEquals("select vtiger_account.accountid, vtiger_account.accountname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.accountname <> 'PK UNA') ) AND vtiger_account.accountid > 0  limit 10 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname,Accounts.website from Contacts where firstname like '%o%' order by firstname desc limit 0,22;");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%') ) AND vtiger_contactdetails.contactid > 0  order by firstname desc   limit 0,22 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname,Accounts.website from Contacts where firstname like '%o%' order by firstname asc");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%') ) AND vtiger_contactdetails.contactid > 0  order by firstname asc  ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname,Accounts.website from Contacts where firstname like '%o%' limit 0,22;");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%') ) AND vtiger_contactdetails.contactid > 0  limit 0,22 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname,Accounts.website from Contacts where firstname like '%o%'");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_accountaccount_id.website as accountswebsite, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%') ) AND vtiger_contactdetails.contactid > 0 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname from Contacts where firstname like '%o%' or firstname like '%e%' or firstname like '%s%'");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%')  OR ( vtiger_contactdetails.firstname LIKE '%e%')  OR ( vtiger_contactdetails.firstname LIKE '%s%') ) AND vtiger_contactdetails.contactid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname, lastname,Accounts.accountname from Contacts where firstname like '%o%' or (firstname like '%e%' and firstname like '%s%')");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.lastname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_contactdetails.accountid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_contactdetails.firstname LIKE '%o%')  OR (( vtiger_contactdetails.firstname LIKE '%e%')  AND ( vtiger_contactdetails.firstname LIKE '%s%') )) AND vtiger_contactdetails.contactid > 0 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname from Contacts where id in ('12x1084','12x1085');");
		$this->assertEquals("SELECT vtiger_contactdetails.firstname,vtiger_contactdetails.contactid FROM vtiger_contactdetails LEFT JOIN vtiger_crmentity ON vtiger_contactdetails.contactid=vtiger_crmentity.crmid   WHERE (vtiger_contactdetails.contactid IN (1084,1085)) AND  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select firstname from Contacts where id not in ('12x1084','12x1085');");
		$this->assertEquals("select vtiger_contactdetails.firstname, vtiger_contactdetails.contactid  FROM vtiger_contactdetails  INNER JOIN vtiger_crmentity ON vtiger_contactdetails.contactid = vtiger_crmentity.crmid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_contactdetails.contactid  NOT IN ('1084','1085')) ) AND vtiger_contactdetails.contactid > 0 ",$actual);
	}

	public function testQueryCountNull() {
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accountname != null;');
		$this->assertEquals("SELECT  COUNT(*) FROM vtiger_account LEFT JOIN vtiger_crmentity ON vtiger_account.accountid=vtiger_crmentity.crmid   WHERE (vtiger_account.accountname != null) AND  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accounts.accountname != null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.accountname IS NOT NULL) ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accountname is not null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.accountname IS NOT NULL AND vtiger_account.accountname != '') ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accounts.accountname is not null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.accountname IS NOT NULL AND vtiger_accountaccount_id.accountname != '') ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accountname = null;');
		$this->assertEquals("SELECT  COUNT(*) FROM vtiger_account LEFT JOIN vtiger_crmentity ON vtiger_account.accountid=vtiger_crmentity.crmid   WHERE (vtiger_account.accountname = null) AND  vtiger_crmentity.deleted=0 LIMIT 100;",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accounts.accountname = null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.accountname IS NULL) ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accountname is null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid   WHERE vtiger_crmentity.deleted=0 AND   (( vtiger_account.accountname IS NULL OR vtiger_account.accountname = '') ) AND vtiger_account.accountid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL('select count(*) from accounts where accounts.accountname is null;');
		$this->assertEquals("select count(*)  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_accountaccount_id.accountname IS NULL OR vtiger_accountaccount_id.accountname = '') ) AND vtiger_account.accountid > 0 ",$actual);
	}

	public function testUsers() {
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select id, account_no, accountname, accounts.accountname from accounts where assigned_user_id !='cbTest testtz' and cf_729 = 'one' limit 0, 10;");
		$this->assertEquals("select vtiger_account.accountid, vtiger_account.account_no, vtiger_account.accountname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid INNER JOIN vtiger_accountscf ON vtiger_account.accountid = vtiger_accountscf.accountid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( (trim(CONCAT(vtiger_users.first_name,' ',vtiger_users.last_name)) <> 'cbTest testtz' or vtiger_groups.groupname <> 'cbTest testtz'))  AND ( vtiger_accountscf.cf_729 = 'one') ) AND vtiger_account.accountid > 0  limit 0, 10 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select id, account_no, accountname, accounts.accountname from accounts where assigned_user_id='cbTest testtz' and cf_729='one' limit 0, 100;");
		$this->assertEquals("select vtiger_account.accountid, vtiger_account.account_no, vtiger_account.accountname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid LEFT JOIN vtiger_users ON vtiger_crmentity.smownerid = vtiger_users.id LEFT JOIN vtiger_groups ON vtiger_crmentity.smownerid = vtiger_groups.groupid INNER JOIN vtiger_accountscf ON vtiger_account.accountid = vtiger_accountscf.accountid LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   (( (trim(CONCAT(vtiger_users.first_name,' ',vtiger_users.last_name)) = 'cbTest testtz' or vtiger_groups.groupname = 'cbTest testtz'))  AND ( vtiger_accountscf.cf_729 = 'one') ) AND vtiger_account.accountid > 0  limit 0, 100 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select id, account_no, accountname, accounts.accountname from accounts where Users.id=20x21199 and cf_729='one' limit 0, 100;");
		$this->assertEquals("select vtiger_account.accountid, vtiger_account.account_no, vtiger_account.accountname, vtiger_accountaccount_id.accountname as accountsaccountname, vtiger_account.accountid  FROM vtiger_account  INNER JOIN vtiger_crmentity ON vtiger_account.accountid = vtiger_crmentity.crmid INNER JOIN vtiger_accountscf ON vtiger_account.accountid = vtiger_accountscf.accountid LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid  LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid  LEFT JOIN vtiger_account AS vtiger_accountaccount_id ON vtiger_accountaccount_id.accountid=vtiger_account.parentid   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_users.id = '21199' or vtiger_groups.groupid = '21199')  AND ( vtiger_accountscf.cf_729 = 'one') ) AND vtiger_account.accountid > 0  limit 0, 100 ",$actual);
	}

	public function testRelations() {
		global $GetRelatedList_ReturnOnlyQuery;
		$GetRelatedList_ReturnOnlyQuery = true;
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select potentialname,Accounts.accountname from Potentials;");
		$this->assertEquals("select vtiger_potential.potentialname, vtiger_accountrelated_to.accountname as accountsaccountname, vtiger_potential.potentialid  FROM vtiger_potential  INNER JOIN vtiger_crmentity ON vtiger_potential.potentialid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountrelated_to ON vtiger_accountrelated_to.accountid=vtiger_potential.related_to   WHERE vtiger_crmentity.deleted=0 AND vtiger_potential.potentialid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select potentialname,Accounts.accountname,Contacts.lastname from Potentials;");
		$this->assertEquals("select vtiger_potential.potentialname, vtiger_accountrelated_to.accountname as accountsaccountname, vtiger_contactdetailsrelated_to.lastname as contactslastname, vtiger_potential.potentialid  FROM vtiger_potential  INNER JOIN vtiger_crmentity ON vtiger_potential.potentialid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountrelated_to ON vtiger_accountrelated_to.accountid=vtiger_potential.related_to LEFT JOIN vtiger_contactdetails AS vtiger_contactdetailsrelated_to ON vtiger_contactdetailsrelated_to.contactid=vtiger_potential.related_to   WHERE vtiger_crmentity.deleted=0 AND vtiger_potential.potentialid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select ticket_title,Accounts.accountname,Contacts.lastname from HelpDesk;");
		$this->assertEquals("select vtiger_troubletickets.title, vtiger_accountparent_id.accountname as accountsaccountname, vtiger_contactdetailsparent_id.lastname as contactslastname, vtiger_troubletickets.ticketid  FROM vtiger_troubletickets  INNER JOIN vtiger_crmentity ON vtiger_troubletickets.ticketid = vtiger_crmentity.crmid LEFT JOIN vtiger_account AS vtiger_accountparent_id ON vtiger_accountparent_id.accountid=vtiger_troubletickets.parent_id LEFT JOIN vtiger_contactdetails AS vtiger_contactdetailsparent_id ON vtiger_contactdetailsparent_id.contactid=vtiger_troubletickets.parent_id   WHERE vtiger_crmentity.deleted=0 AND vtiger_troubletickets.ticketid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from projecttask where related.project='33x6613';");
		$this->assertEquals("select vtiger_projecttask.projecttaskname,vtiger_projecttask.projecttasktype,vtiger_projecttask.projecttaskpriority,vtiger_projecttask.projectid,vtiger_crmentity.smownerid as assigned_user_id,vtiger_crmentity.smownerid,vtiger_projecttask.projecttasknumber,vtiger_projecttask.projecttask_no,vtiger_projecttask.projecttaskprogress,vtiger_projecttask.projecttaskhours,vtiger_projecttask.startdate,vtiger_projecttask.enddate,vtiger_crmentity.createdtime,vtiger_crmentity.modifiedtime,vtiger_crmentity.modifiedby,vtiger_crmentity.description,vtiger_projecttask.email,vtiger_projecttask.projecttaskid FROM vtiger_projecttask INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_projecttask.projecttaskid INNER JOIN vtiger_project ON (vtiger_project.projectid = vtiger_projecttask.projectid) LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_projecttaskcf on vtiger_projecttaskcf.projecttaskid = vtiger_projecttask.projecttaskid  WHERE vtiger_crmentity.deleted = 0 AND vtiger_project.projectid = 6613",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from projecttask where related.project='33x6613' and projecttaskname='tttt';");
		$this->assertEquals("select vtiger_projecttask.projecttaskname,vtiger_projecttask.projecttasktype,vtiger_projecttask.projecttaskpriority,vtiger_projecttask.projectid,vtiger_crmentity.smownerid as assigned_user_id,vtiger_crmentity.smownerid,vtiger_projecttask.projecttasknumber,vtiger_projecttask.projecttask_no,vtiger_projecttask.projecttaskprogress,vtiger_projecttask.projecttaskhours,vtiger_projecttask.startdate,vtiger_projecttask.enddate,vtiger_crmentity.createdtime,vtiger_crmentity.modifiedtime,vtiger_crmentity.modifiedby,vtiger_crmentity.description,vtiger_projecttask.email,vtiger_projecttask.projecttaskid FROM vtiger_projecttask INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_projecttask.projecttaskid INNER JOIN vtiger_project ON (vtiger_project.projectid = vtiger_projecttask.projectid) LEFT JOIN vtiger_users ON vtiger_users.id = vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_projecttaskcf on vtiger_projecttaskcf.projecttaskid = vtiger_projecttask.projecttaskid  WHERE vtiger_crmentity.deleted = 0 AND vtiger_project.projectid = 6613 and  projecttaskname='tttt' ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from documents where related.accounts='11x75';");
		$this->assertEquals("select vtiger_notes.title,vtiger_crmentity.createdtime,vtiger_crmentity.modifiedtime,vtiger_crmentity.smownerid as assigned_user_id,vtiger_crmentity.smownerid,vtiger_notes.notecontent,vtiger_notes.filetype,vtiger_notes.filesize,vtiger_notes.filelocationtype,vtiger_notes.fileversion,vtiger_notes.filestatus,vtiger_notes.filedownloadcount,vtiger_notes.folderid,vtiger_notes.note_no,vtiger_crmentity.modifiedby,vtiger_notes.notesid  from vtiger_notes inner join vtiger_senotesrel on vtiger_senotesrel.notesid= vtiger_notes.notesid left join vtiger_notescf ON vtiger_notescf.notesid= vtiger_notes.notesid inner join vtiger_crmentity on vtiger_crmentity.crmid= vtiger_notes.notesid and vtiger_crmentity.deleted=0 inner join vtiger_crmentity crm2 on crm2.crmid=vtiger_senotesrel.crmid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_seattachmentsrel on vtiger_seattachmentsrel.crmid =vtiger_notes.notesid left join vtiger_attachments on vtiger_seattachmentsrel.attachmentsid = vtiger_attachments.attachmentsid left join vtiger_users on vtiger_crmentity.smownerid= vtiger_users.id where crm2.crmid=75",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from documents where filelocationtype='E' and related.contacts='12x1084';");
		$this->assertEquals("select vtiger_notes.title,vtiger_crmentity.createdtime,vtiger_crmentity.modifiedtime,vtiger_crmentity.smownerid as assigned_user_id,vtiger_crmentity.smownerid,vtiger_notes.notecontent,vtiger_notes.filetype,vtiger_notes.filesize,vtiger_notes.filelocationtype,vtiger_notes.fileversion,vtiger_notes.filestatus,vtiger_notes.filedownloadcount,vtiger_notes.folderid,vtiger_notes.note_no,vtiger_crmentity.modifiedby,vtiger_notes.notesid  from vtiger_notes inner join vtiger_senotesrel on vtiger_senotesrel.notesid= vtiger_notes.notesid left join vtiger_notescf ON vtiger_notescf.notesid= vtiger_notes.notesid inner join vtiger_crmentity on vtiger_crmentity.crmid= vtiger_notes.notesid and vtiger_crmentity.deleted=0 inner join vtiger_crmentity crm2 on crm2.crmid=vtiger_senotesrel.crmid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_seattachmentsrel on vtiger_seattachmentsrel.crmid =vtiger_notes.notesid left join vtiger_attachments on vtiger_seattachmentsrel.attachmentsid = vtiger_attachments.attachmentsid left join vtiger_users on vtiger_crmentity.smownerid= vtiger_users.id where crm2.crmid=1084 and  filelocationtype='E' ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from documents where (related.Contacts='12x1084') AND (filelocationtype LIKE '%I%') LIMIT 5;");
		$this->assertEquals("select vtiger_notes.title,vtiger_crmentity.createdtime,vtiger_crmentity.modifiedtime,vtiger_crmentity.smownerid as assigned_user_id,vtiger_crmentity.smownerid,vtiger_notes.notecontent,vtiger_notes.filetype,vtiger_notes.filesize,vtiger_notes.filelocationtype,vtiger_notes.fileversion,vtiger_notes.filestatus,vtiger_notes.filedownloadcount,vtiger_notes.folderid,vtiger_notes.note_no,vtiger_crmentity.modifiedby,vtiger_notes.notesid  from vtiger_notes inner join vtiger_senotesrel on vtiger_senotesrel.notesid= vtiger_notes.notesid left join vtiger_notescf ON vtiger_notescf.notesid= vtiger_notes.notesid inner join vtiger_crmentity on vtiger_crmentity.crmid= vtiger_notes.notesid and vtiger_crmentity.deleted=0 inner join vtiger_crmentity crm2 on crm2.crmid=vtiger_senotesrel.crmid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_seattachmentsrel on vtiger_seattachmentsrel.crmid =vtiger_notes.notesid left join vtiger_attachments on vtiger_seattachmentsrel.attachmentsid = vtiger_attachments.attachmentsid left join vtiger_users on vtiger_crmentity.smownerid= vtiger_users.id where crm2.crmid=1084 AND  (filelocationtype LIKE '%I%') LIMIT 5 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from modcomments where related.helpdesk='17x2636';");
		$this->assertEquals("select
						concat(case when (ownertype = 'user') then '19x' else '12x' end,ownerid) as creator,
						concat(case when (ownertype = 'user') then '19x' else '12x' end,ownerid) as assigned_user_id,
						'TicketComments' as setype,
						createdtime,
						createdtime as modifiedtime,
						0 as id,
						comments as commentcontent, 
						'17x2636' as related_to, 
						'' as parent_comments,
						ownertype,
						case when (ownertype = 'user') then vtiger_users.user_name else vtiger_portalinfo.user_name end as owner_name 
					 from vtiger_ticketcomments
					 left join vtiger_users on vtiger_users.id = ownerid
					 left join vtiger_portalinfo on vtiger_portalinfo.id = ownerid
					 where ticketid=2636",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select * from modcomments where related.helpdesk='17x2636' and commentcontent like 'hdcc%';");
		$this->assertEquals("select
						concat(case when (ownertype = 'user') then '19x' else '12x' end,ownerid) as creator,
						concat(case when (ownertype = 'user') then '19x' else '12x' end,ownerid) as assigned_user_id,
						'TicketComments' as setype,
						createdtime,
						createdtime as modifiedtime,
						0 as id,
						comments as commentcontent, 
						'17x2636' as related_to, 
						'' as parent_comments,
						ownertype,
						case when (ownertype = 'user') then vtiger_users.user_name else vtiger_portalinfo.user_name end as owner_name 
					 from vtiger_ticketcomments
					 left join vtiger_users on vtiger_users.id = ownerid
					 left join vtiger_portalinfo on vtiger_portalinfo.id = ownerid
					 where ticketid=2636 and  comments like 'hdcc%' ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select productname from products where related.products='14x2616';");
		$this->assertEquals("select vtiger_products.productname FROM vtiger_products INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_products.productid INNER JOIN vtiger_productcf ON vtiger_productcf.productid = vtiger_products.productid LEFT JOIN vtiger_seproductsrel ON vtiger_seproductsrel.crmid = vtiger_products.productid AND vtiger_seproductsrel.setype='Products' LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_producttaxrel on vtiger_producttaxrel.productid = vtiger_products.productid  WHERE vtiger_crmentity.deleted = 0 AND vtiger_seproductsrel.productid = 2616 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select productname from products where related.contacts='12x1084';");
		$this->assertEquals("select vtiger_products.productname FROM vtiger_products INNER JOIN vtiger_seproductsrel ON vtiger_seproductsrel.productid=vtiger_products.productid and vtiger_seproductsrel.setype=\"Contacts\" INNER JOIN vtiger_productcf ON vtiger_products.productid = vtiger_productcf.productid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_products.productid INNER JOIN vtiger_contactdetails ON vtiger_contactdetails.contactid = vtiger_seproductsrel.crmid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_producttaxrel on vtiger_producttaxrel.productid = vtiger_products.productid  WHERE vtiger_contactdetails.contactid = 1084 and vtiger_crmentity.deleted = 0",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select productname from products where related.contacts='12x1084' and productcategory='Software';");
		$this->assertEquals("select vtiger_products.productname FROM vtiger_products INNER JOIN vtiger_seproductsrel ON vtiger_seproductsrel.productid=vtiger_products.productid and vtiger_seproductsrel.setype=\"Contacts\" INNER JOIN vtiger_productcf ON vtiger_products.productid = vtiger_productcf.productid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_products.productid INNER JOIN vtiger_contactdetails ON vtiger_contactdetails.contactid = vtiger_seproductsrel.crmid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_producttaxrel on vtiger_producttaxrel.productid = vtiger_products.productid  WHERE vtiger_contactdetails.contactid = 1084 and vtiger_crmentity.deleted = 0 and  productcategory='Software' ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("Select productname from Products where related.Contacts='12x1084' LIMIT 5;");
		$this->assertEquals("select vtiger_products.productname FROM vtiger_products INNER JOIN vtiger_seproductsrel ON vtiger_seproductsrel.productid=vtiger_products.productid and vtiger_seproductsrel.setype=\"Contacts\" INNER JOIN vtiger_productcf ON vtiger_products.productid = vtiger_productcf.productid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_products.productid INNER JOIN vtiger_contactdetails ON vtiger_contactdetails.contactid = vtiger_seproductsrel.crmid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_producttaxrel on vtiger_producttaxrel.productid = vtiger_products.productid  WHERE vtiger_contactdetails.contactid = 1084 and vtiger_crmentity.deleted = 0 LIMIT 5 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("Select productname from Products where related.Contacts='12x1084' order by productname LIMIT 5;");
		$this->assertEquals("select vtiger_products.productname FROM vtiger_products INNER JOIN vtiger_seproductsrel ON vtiger_seproductsrel.productid=vtiger_products.productid and vtiger_seproductsrel.setype=\"Contacts\" INNER JOIN vtiger_productcf ON vtiger_products.productid = vtiger_productcf.productid INNER JOIN vtiger_crmentity ON vtiger_crmentity.crmid = vtiger_products.productid INNER JOIN vtiger_contactdetails ON vtiger_contactdetails.contactid = vtiger_seproductsrel.crmid LEFT JOIN vtiger_users ON vtiger_users.id=vtiger_crmentity.smownerid LEFT JOIN vtiger_groups ON vtiger_groups.groupid = vtiger_crmentity.smownerid left join vtiger_producttaxrel on vtiger_producttaxrel.productid = vtiger_products.productid  WHERE vtiger_contactdetails.contactid = 1084 and vtiger_crmentity.deleted = 0 order by vtiger_products.productname LIMIT 5 ",$actual);

		$actual = self::$vtModuleOperation->wsVTQL2SQL("select Contacts.firstname,Salesorder.subject,amount,paid from cobropago where Contacts.homephone='902886938';");
		$this->assertEquals("select vtiger_contactdetailsparent_id.firstname as contactsfirstname, vtiger_salesorderrelated_id.subject as salesordersubject, vtiger_cobropago.amount, vtiger_cobropago.paid, vtiger_cobropago.cobropagoid  FROM vtiger_cobropago  INNER JOIN vtiger_crmentity ON vtiger_cobropago.cobropagoid = vtiger_crmentity.crmid LEFT JOIN vtiger_contactsubdetails AS vtiger_contactsubdetailsparent_id ON vtiger_contactsubdetailsparent_id.contactsubscriptionid=vtiger_cobropago.parent_id LEFT JOIN vtiger_contactdetails AS vtiger_contactdetailsparent_id ON vtiger_contactdetailsparent_id.contactid=vtiger_cobropago.parent_id LEFT JOIN vtiger_salesorder AS vtiger_salesorderrelated_id ON vtiger_salesorderrelated_id.salesorderid=vtiger_cobropago.related_id   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_contactsubdetailsparent_id.homephone = '902886938') ) AND vtiger_cobropago.cobropagoid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select Products.productname,ticket_title from HelpDesk where Products.productname > = 'áé íÑÇ';");
		$this->assertEquals("select vtiger_productsproduct_id.productname as productsproductname, vtiger_troubletickets.title, vtiger_troubletickets.ticketid  FROM vtiger_troubletickets  INNER JOIN vtiger_crmentity ON vtiger_troubletickets.ticketid = vtiger_crmentity.crmid LEFT JOIN vtiger_products AS vtiger_productsproduct_id ON vtiger_productsproduct_id.productid=vtiger_troubletickets.product_id   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_productsproduct_id.productname >= 'áé íÑÇ') ) AND vtiger_troubletickets.ticketid > 0 ",$actual);
		$actual = self::$vtModuleOperation->wsVTQL2SQL("select Products.productname,ticket_title from HelpDesk where Products.productname > = 'áé> =íÑÇ';");
		$this->assertEquals("select vtiger_productsproduct_id.productname as productsproductname, vtiger_troubletickets.title, vtiger_troubletickets.ticketid  FROM vtiger_troubletickets  INNER JOIN vtiger_crmentity ON vtiger_troubletickets.ticketid = vtiger_crmentity.crmid LEFT JOIN vtiger_products AS vtiger_productsproduct_id ON vtiger_productsproduct_id.productid=vtiger_troubletickets.product_id   WHERE vtiger_crmentity.deleted=0 AND   ((vtiger_productsproduct_id.productname >= 'áé> =íÑÇ') ) AND vtiger_troubletickets.ticketid > 0 ",$actual);
		$GetRelatedList_ReturnOnlyQuery = false;
	}

}
?>