
const puppeteer = require('puppeteer');
process.env.CHROME_BIN = puppeteer.executablePath();

module.exports = function(config) {
  config.set({
    basePath: '../../',
    frameworks: ['jasmine'],
    files: [
      'build/coreBOSTests/loadcorebos.js',
      'include/components/ldsprompt.js',
      'include/components/ldsmodal.js',
      'include/components/checkboxrenderer.js',
      'include/components/loadjs.js',
      'include/jquery/jquery.js',
      'include/jquery/jquery-ui.js',
      'include/dompurify/purify.min.js',
      'include/js/en_us.lang.js',
      'include/js/vtlib.js',
      'include/js/general.js',
      'include/js/advancefilter.js',
      'include/js/customview.js',
      'include/js/dedup.js',
      'include/js/dtlviewajax.js',
      'include/js/FieldDependencies.js',
      'include/js/FieldDepFunc.js',
      'include/js/Inventory.js',
      'include/js/ListView.js',
      'include/js/Mail.js',
      'include/js/massive.js',
      'include/js/masterdetailgrid.js',
      'include/js/Merge.js',
      'include/js/notebook.js',
      'include/js/notificationPopup.js',
      'include/js/PasswordManagement.js',
      'include/js/picklist.js',
      'include/js/popup.js',
      'include/js/QuickCreate.js',
      'include/js/RelatedLists.js',
      'include/js/search.js',
      'modules/PriceBooks/PriceBooks.js',
      'modules/cbCalendar/cbCalendar.js',
      'modules/cbCalendar/script.js',
      'modules/BusinessActions/BusinessActions.js',
      'modules/ModComments/ModComments.js',
      'modules/ModComments/ModCommentsCommon.js',
      'modules/Calendar4You/Calendar4You.js',
      'modules/Assets/Assets.js',
      'modules/evvtgendoc/evvtgendoc.js',
      'modules/Contacts/Contacts.js',
      'modules/Invoice/Invoice.js',
      'modules/Users/ChangePassword.js',
      'modules/Users/Users.js',
      'modules/SalesOrder/SalesOrder.js',
      'modules/evvtMenu/evvtMenu.js',
      'modules/RecycleBin/RecycleBin.js',
      'modules/Leads/Leads.js',
      'modules/PickList/DependencyPicklist.js',
      'modules/PickList/PickList.js',
      'modules/Utilities/Utilities.js',
      'modules/Reports/Reports.js',
      'modules/MsgTemplate/MsgTemplate.js',
      'modules/Documents/Documents.js',
      'modules/cbupdater/cbupdater.js',
      'modules/Webforms/Webforms.js',
      'modules/Accounts/Accounts.js',
      'modules/Emails/Emails.js',
      'modules/cbMap/cbMap.js',
      'modules/Vendors/Vendors.js',
      'modules/Products/Products.js',
      'modules/HelpDesk/HelpDesk.js',
      'modules/Potentials/Potentials.js',
      'modules/CronTasks/CronTasks.js',
      'modules/PurchaseOrder/PurchaseOrder.js',
      'modules/Campaigns/Campaigns.js',
      'modules/Import/resources/ImportStep2.js',
      'modules/Import/resources/Import.js',
      'modules/Settings/Settings.js',
      'modules/Settings/profilePrivileges.js',
      'modules/MailManager/MailManager.js',
      'modules/Services/Services.js',
      'modules/CustomView/CustomView.js',
      'modules/cbQuestion/cbQuestion.js',
      'modules/Tooltip/TooltipHeaderScript.js',
      'modules/Tooltip/TooltipSettings.js',
      'modules/Quotes/Quotes.js',
      'massedit-worker.js',
      'themes/login/login.js',
      'build/coreBOSTests/spec/**/*.js'
    ],
    browsers: ['ChromeHeadless'],
    singleRun: true,
    plugins: [
      'karma-jasmine',
      'karma-chrome-launcher',
      'karma-coverage'
    ],
    reporters: ['progress', 'coverage'],
    coverageReporter: {
      includeAllSources: true,
      type : 'lcov',
      dir: 'build/coreBOSTests/coverage'
    },
    preprocessors: { 
      'include/components/ldsprompt.js': ['coverage'],
      'include/components/ldsmodal.js': ['coverage'],
      'include/components/checkboxrenderer.js': ['coverage'],
      'include/components/loadjs.js': ['coverage'],
      'include/js/en_us.lang.js': ['coverage'],
      'include/js/vtlib.js': ['coverage'],
      'include/js/general.js': ['coverage'],
      'include/js/advancefilter.js': ['coverage'],
      'include/js/customview.js': ['coverage'],
      'include/js/dedup.js': ['coverage'],
      'include/js/dtlviewajax.js': ['coverage'],
      'include/js/FieldDependencies.js': ['coverage'],
      'include/js/FieldDepFunc.js': ['coverage'],
      'include/js/Inventory.js': ['coverage'],
      'include/js/ListView.js': ['coverage'],
      'include/js/Mail.js': ['coverage'],
      'include/js/massive.js': ['coverage'],
      'include/js/masterdetailgrid.js': ['coverage'],
      'include/js/Merge.js': ['coverage'],
      'include/js/notebook.js': ['coverage'],
      'include/js/notificationPopup.js': ['coverage'],
      'include/js/PasswordManagement.js': ['coverage'],
      'include/js/picklist.js': ['coverage'],
      'include/js/popup.js': ['coverage'],
      'include/js/QuickCreate.js': ['coverage'],
      'include/js/RelatedLists.js': ['coverage'],
      'include/js/search.js': ['coverage'],
      'modules/PriceBooks/PriceBooks.js': ['coverage'],
      'modules/cbCalendar/cbCalendar.js': ['coverage'],
      'modules/cbCalendar/script.js': ['coverage'],
      'modules/BusinessActions/BusinessActions.js': ['coverage'],
      'modules/ModComments/ModComments.js': ['coverage'],
      'modules/ModComments/ModCommentsCommon.js': ['coverage'],
      'modules/Calendar4You/Calendar4You.js': ['coverage'],
      'modules/Assets/Assets.js': ['coverage'],
      'modules/evvtgendoc/evvtgendoc.js': ['coverage'],
      'modules/Contacts/Contacts.js': ['coverage'],
      'modules/Invoice/Invoice.js': ['coverage'],
      'modules/Users/ChangePassword.js': ['coverage'],
      'modules/Users/Users.js': ['coverage'],
      'modules/SalesOrder/SalesOrder.js': ['coverage'],
      'modules/evvtMenu/evvtMenu.js': ['coverage'],
      'modules/RecycleBin/RecycleBin.js': ['coverage'],
      'modules/Leads/Leads.js': ['coverage'],
      'modules/PickList/DependencyPicklist.js': ['coverage'],
      'modules/PickList/PickList.js': ['coverage'],
      'modules/Utilities/Utilities.js': ['coverage'],
      'modules/Reports/Reports.js': ['coverage'],
      'modules/MsgTemplate/MsgTemplate.js': ['coverage'],
      'modules/Documents/Documents.js': ['coverage'],
      'modules/cbupdater/cbupdater.js': ['coverage'],
      'modules/Webforms/Webforms.js': ['coverage'],
      'modules/Accounts/Accounts.js': ['coverage'],
      'modules/Emails/Emails.js': ['coverage'],
      'modules/cbMap/cbMap.js': ['coverage'],
      'modules/Vendors/Vendors.js': ['coverage'],
      'modules/Products/Products.js': ['coverage'],
      'modules/HelpDesk/HelpDesk.js': ['coverage'],
      'modules/Potentials/Potentials.js': ['coverage'],
      'modules/CronTasks/CronTasks.js': ['coverage'],
      'modules/PurchaseOrder/PurchaseOrder.js': ['coverage'],
      'modules/Campaigns/Campaigns.js': ['coverage'],
      'modules/Import/resources/ImportStep2.js': ['coverage'],
      'modules/Import/resources/Import.js': ['coverage'],
      'modules/Settings/Settings.js': ['coverage'],
      'modules/Settings/profilePrivileges.js': ['coverage'],
      'modules/MailManager/MailManager.js': ['coverage'],
      'modules/Services/Services.js': ['coverage'],
      'modules/CustomView/CustomView.js': ['coverage'],
      'modules/cbQuestion/cbQuestion.js': ['coverage'],
      'modules/Tooltip/TooltipHeaderScript.js': ['coverage'],
      'modules/Tooltip/TooltipSettings.js': ['coverage'],
      'modules/Quotes/Quotes.js': ['coverage'],
      'massedit-worker.js': ['coverage'],
      'themes/login/login.js': ['coverage']
    }
  });
};